/* automatically generated by rust-bindgen 0.58.1 */

use
super::*;

pub const ADC_DMA_CHANNEL: u32 = 1;
pub const ADC_CHANNEL_MAX: u32 = 12;
pub type __int32_t = ::cty::c_int;
pub type __uint32_t = ::cty::c_uint;
pub type bl_adc_cb_t = ::core::option::Option<
    unsafe extern "C" fn(mode: ::cty::c_int, data_ptr: *mut u32, data_size: u32),
>;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct adc_ctx {
    pub mode: ::cty::c_int,
    pub channel_data: *mut u32,
    pub adc_lli: *mut ::cty::c_void,
    pub lli_flag: ::cty::c_int,
    pub chan_init_table: u32,
    pub data_size: u32,
    pub cb: bl_adc_cb_t,
}
impl Default for adc_ctx {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type adc_ctx_t = adc_ctx;
#[safe_wrap(_)] extern "C" {
    pub fn bl_adc_init(mode: ::cty::c_int, gpio_num: ::cty::c_int) -> ::cty::c_int;
}
#[safe_wrap(_)] extern "C" {
    pub fn bl_adc_dma_init(mode: ::cty::c_int, data_num: u32) -> ::cty::c_int;
}
#[safe_wrap(_)] extern "C" {
    pub fn bl_adc_start() -> ::cty::c_int;
}
#[safe_wrap(_)] extern "C" {
    pub fn bl_adc_gpio_init(gpio_num: ::cty::c_int) -> ::cty::c_int;
}
#[safe_wrap(_)] extern "C" {
    pub fn bl_adc_get_channel_by_gpio(gpio_num: ::cty::c_int) -> ::cty::c_int;
}
#[safe_wrap(_)] extern "C" {
    pub fn bl_adc_freq_init(mode: ::cty::c_int, freq: u32) -> ::cty::c_int;
}
#[safe_wrap(_)] extern "C" {
    pub fn bl_adc_parse_data(
        parr: *mut u32,
        data_size: ::cty::c_int,
        channel: ::cty::c_int,
        raw_flag: ::cty::c_int,
    ) -> i32;
}
