/* automatically generated by rust-bindgen 0.58.1 */

use
super::*;

#[repr(C)]
#[derive(Copy, Clone)]
pub struct _gpio_ctx_desc {
    pub next: *mut _gpio_ctx_desc,
    pub gpio_handler: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ::cty::c_void)>,
    pub arg: *mut ::cty::c_void,
    pub gpioPin: u8,
    pub intCtrlMod: u8,
    pub intTrgMod: u8,
}
impl Default for _gpio_ctx_desc {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
pub type gpio_ctx_t = _gpio_ctx_desc;
#[safe_wrap(attr)] extern "C" {
    pub fn bl_gpio_enable_output(pin: u8, pullup: u8, pulldown: u8) -> ::cty::c_int;
}
#[safe_wrap(attr)] extern "C" {
    pub fn bl_gpio_enable_input(pin: u8, pullup: u8, pulldown: u8) -> ::cty::c_int;
}
#[safe_wrap(attr)] extern "C" {
    pub fn bl_gpio_output_set(pin: u8, value: u8) -> ::cty::c_int;
}
#[safe_wrap(attr)] extern "C" {
    pub fn bl_gpio_input_get(pin: u8, value: *mut u8) -> ::cty::c_int;
}
#[safe_wrap(attr)] extern "C" {
    pub fn bl_gpio_input_get_value(pin: u8) -> ::cty::c_int;
}
#[safe_wrap(attr)] extern "C" {
    pub fn bl_gpio_int_clear(gpioPin: u8, intClear: u8) -> ::cty::c_int;
}
#[safe_wrap(attr)] extern "C" {
    pub fn bl_gpio_intmask(gpiopin: u8, mask: u8);
}
#[safe_wrap(attr)] extern "C" {
    pub fn bl_gpio_register(pstnode: *mut gpio_ctx_t);
}
