/* automatically generated by rust-bindgen 0.58.1 */

use
super::*;

pub type __uint8_t = ::cty::c_uchar;
pub type __uint32_t = ::cty::c_uint;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct spi_config_t {
    pub mode: u8,
    pub freq: u32,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct spi_dev_t {
    pub port: u8,
    pub config: spi_config_t,
    pub priv_: *mut ::cty::c_void,
}
impl Default for spi_dev_t {
    fn default() -> Self {
        unsafe { ::core::mem::zeroed() }
    }
}
#[safe_wrap(_)] extern "C" {
    pub fn spi_init(
        spi: *mut spi_dev_t,
        port: u8,
        mode: u8,
        polar_phase: u8,
        freq: u32,
        tx_dma_ch: u8,
        rx_dma_ch: u8,
        pin_clk: u8,
        pin_cs: u8,
        pin_mosi: u8,
        pin_miso: u8,
    ) -> ::cty::c_int;
}
